LOCAL_PATH := $(call my-dir)


#libloc_api
include $(CLEAR_VARS)
LOCAL_MODULE := libloc_api
LOCAL_SRC_FILES := lib/libloc_api.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libwmsts
include $(CLEAR_VARS)
LOCAL_MODULE := libwmsts
LOCAL_SRC_FILES := lib/libwmsts.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libpbmlib
include $(CLEAR_VARS)
LOCAL_MODULE := libpbmlib
LOCAL_SRC_FILES := lib/libpbmlib.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#liboncrpc
include $(CLEAR_VARS)
LOCAL_MODULE := liboncrpc
LOCAL_SRC_FILES := lib/liboncrpc.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libril-qc-1
include $(CLEAR_VARS)
LOCAL_MODULE := libril-qc-1
LOCAL_SRC_FILES := lib/libril-qc-1.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libril-qcril-hook-oem
include $(CLEAR_VARS)
LOCAL_MODULE := libril-qcril-hook-oem
LOCAL_SRC_FILES := lib/libril-qcril-hook-oem.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libnv
include $(CLEAR_VARS)
LOCAL_MODULE := libnv
LOCAL_SRC_FILES := lib/libnv.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libdss
include $(CLEAR_VARS)
LOCAL_MODULE := libdss
LOCAL_SRC_FILES := lib/libdss.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libdll
include $(CLEAR_VARS)
LOCAL_MODULE := libdll
LOCAL_SRC_FILES := lib/libdll.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libdsm
include $(CLEAR_VARS)
LOCAL_MODULE := libdsm
LOCAL_SRC_FILES := lib/libdsm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libcm
include $(CLEAR_VARS)
LOCAL_MODULE := libcm
LOCAL_SRC_FILES := lib/libcm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libgstk_exp
include $(CLEAR_VARS)
LOCAL_MODULE := libgstk_exp
LOCAL_SRC_FILES := lib/libgstk_exp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libcamera
include $(CLEAR_VARS)
LOCAL_MODULE := libcamera
LOCAL_SRC_FILES := lib/libcamera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libmmgsdilib
include $(CLEAR_VARS)
LOCAL_MODULE := libmmgsdilib
LOCAL_SRC_FILES := lib/libmmgsdilib.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libdiag
include $(CLEAR_VARS)
LOCAL_MODULE := libdiag
LOCAL_SRC_FILES := lib/libdiag.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libauth
include $(CLEAR_VARS)
LOCAL_MODULE := libauth
LOCAL_SRC_FILES := lib/libauth.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libatu
include $(CLEAR_VARS)
LOCAL_MODULE := libatu
LOCAL_SRC_FILES := lib/libatu.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libgsl
include $(CLEAR_VARS)
LOCAL_MODULE := libgsl
LOCAL_SRC_FILES := lib/libgsl.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libqmi
include $(CLEAR_VARS)
LOCAL_MODULE := libqmi
LOCAL_SRC_FILES := lib/libqmi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#reset
include $(CLEAR_VARS)
LOCAL_MODULE := reset
LOCAL_SRC_FILES := lib/modules/reset.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)

#dhd_test
include $(CLEAR_VARS)
LOCAL_MODULE := dhd_test
LOCAL_SRC_FILES := lib/modules/dhd_test.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)

#dhd
include $(CLEAR_VARS)
LOCAL_MODULE := dhd
LOCAL_SRC_FILES := lib/modules/dhd.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/modules
include $(BUILD_PREBUILT)

#liboem_rapi
include $(CLEAR_VARS)
LOCAL_MODULE := liboem_rapi
LOCAL_SRC_FILES := lib/liboem_rapi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libgsdi_exp
include $(CLEAR_VARS)
LOCAL_MODULE := libgsdi_exp
LOCAL_SRC_FILES := lib/libgsdi_exp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libqueue
include $(CLEAR_VARS)
LOCAL_MODULE := libqueue
LOCAL_SRC_FILES := lib/libqueue.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libwms
include $(CLEAR_VARS)
LOCAL_MODULE := libwms
LOCAL_SRC_FILES := lib/libwms.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
include $(BUILD_PREBUILT)

#libGLESv2_adreno200
include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv2_adreno200
LOCAL_SRC_FILES := lib/egl/libGLESv2_adreno200.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
include $(BUILD_PREBUILT)

#libq3dtools_adreno200
include $(CLEAR_VARS)
LOCAL_MODULE := libq3dtools_adreno200
LOCAL_SRC_FILES := lib/egl/libq3dtools_adreno200.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
include $(BUILD_PREBUILT)

#libEGL_adreno200
include $(CLEAR_VARS)
LOCAL_MODULE := libEGL_adreno200
LOCAL_SRC_FILES := lib/egl/libEGL_adreno200.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
include $(BUILD_PREBUILT)

#libGLESv1_CM_adreno200
include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv1_CM_adreno200
LOCAL_SRC_FILES := lib/egl/libGLESv1_CM_adreno200.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
include $(BUILD_PREBUILT)

